# Este es el docker compose para levantar un contenedor de Oracle
# falta probar

# COMANDO
# docker compose -f ./oracle/docker-compose.yml up -d
version: '3.8'

services:
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    container_name: oracle
    restart: unless-stopped
    environment:
      ORACLE_DATABASE: "cafeteria"  # Nombre de la base de datos que se creará
    ports:
      - "1521:1521"  # Solo el puerto de Oracle
    volumes:
      - ./cafeteria.sql:/docker-entrypoint-initdb.d/cafeteria.sql  # Importación del archivo SQL
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 1G
